language: go

go:
  - 1.11.x
  - 1.12.x

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.28.1/bazel_0.28.1-linux-x86_64.deb
  - sha256sum -c tools/bazel_0.28.1-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_0.28.1-linux-x86_64.deb

before_script:
  - go get -u honnef.co/go/tools/cmd/staticcheck

script:
  - staticcheck ./...
  - go test -race -v -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
