language: go

go:
  - 1.11.x
  - 1.12.x

before_script:
  - go get -u honnef.co/go/tools/cmd/staticcheck

script:
  - export GO_FILES=$(go list ./... | grep -v /vendor/ | grep -v /testdata/)
  - staticcheck $GO_FILES
  - go test -race -v -coverprofile=coverage.txt -covermode=atomic $GO_FILES

after_success:
  - bash <(curl -s https://codecov.io/bash)
