load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["z_bindata.go"],
    importpath = "github.com/bongnv/kitgen/templates",
    visibility = ["//visibility:public"],
)
